/**
* OpenAPI Petstore
* This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Tag.h
 *
 * A tag for a pet
 */

#ifndef Tag_H_
#define Tag_H_


#include <string>
#include <json/json.h>

namespace org::openapitools::server::model
{

/// <summary>
/// A tag for a pet
/// </summary>
class  Tag
{
public:
    Tag();
    virtual ~Tag() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const Tag& rhs) const;
    bool operator!=(const Tag& rhs) const;

    /////////////////////////////////////////////
    /// Tag members

    /// <summary>
    /// 
    /// </summary>
    std::int64_t getId() const;
    void setId(std::int64_t const value);
    bool idIsSet() const;
    void unsetId();
    /// <summary>
    /// 
    /// </summary>
    std::string getName() const;
    void setName(std::string const& value);
    bool nameIsSet() const;
    void unsetName();

    friend  void to_json(Json::Value& j, const Tag& o);
    friend  void from_json(const Json::Value& j, Tag& o);
protected:
    std::int64_t m_Id;
    bool m_IdIsSet;
    std::string m_Name;
    bool m_NameIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* Tag_H_ */
