generatorName: cpp-drogon-server
outputDir: /home/jbjoannic/Dev/vslam/drogonApp2
inputSpec: /home/jbjoannic/Dev/vslam/generation/api/openapi.yaml
templateDir: modules/openapi-generator/src/main/resources/cpp-drogon
additionalProperties:
  hideGenerationTimestamp: "true"
  useStructModel: "true"
