generatorName: cpp-drogon-server
outputDir: /home/jbjoannic/Dev/video-manager/drogonApp
inputSpec: /home/jbjoannic/Dev/video-manager/api/openapi.yaml
templateDir: modules/openapi-generator/src/main/resources/cpp-drogon
additionalProperties:
  hideGenerationTimestamp: "true"
  useStructModel: "true"
