/**
* OpenAPI Petstore
* This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "PetApiImpl.h"

namespace org::openapitools::server::api
{

/* ------------------------------------------------------------------ */
/*  addPet                                                   */
/* ------------------------------------------------------------------ */
void PetApiImpl::add_pet(
    const Pet &pet
    , 
    addPetResponse &response)
{
    /* TODO: business logic.                                             *
     * Replace the placeholder below with real handling.                 */

    response = std::integral_constant<
        drogon::HttpStatusCode,
        drogon::k501NotImplemented>{};
}
/* ------------------------------------------------------------------ */
/*  deletePet                                                   */
/* ------------------------------------------------------------------ */
void PetApiImpl::delete_pet(
    const std::int64_t &path_petId, 
        const std::string &header_apiKey
    , 
    deletePetResponse &response)
{
    /* TODO: business logic.                                             *
     * Replace the placeholder below with real handling.                 */

    response = std::integral_constant<
        drogon::HttpStatusCode,
        drogon::k501NotImplemented>{};
}
/* ------------------------------------------------------------------ */
/*  findPetsByStatus                                                   */
/* ------------------------------------------------------------------ */
void PetApiImpl::find_pets_by_status(
    const std::optional<std::vector<std::string>> &query_status
    , 
    findPetsByStatusResponse &response)
{
    /* TODO: business logic.                                             *
     * Replace the placeholder below with real handling.                 */

    response = std::integral_constant<
        drogon::HttpStatusCode,
        drogon::k501NotImplemented>{};
}
/* ------------------------------------------------------------------ */
/*  findPetsByTags                                                   */
/* ------------------------------------------------------------------ */
void PetApiImpl::find_pets_by_tags(
    const std::optional<std::vector<std::string>> &query_tags
    , 
    findPetsByTagsResponse &response)
{
    /* TODO: business logic.                                             *
     * Replace the placeholder below with real handling.                 */

    response = std::integral_constant<
        drogon::HttpStatusCode,
        drogon::k501NotImplemented>{};
}
/* ------------------------------------------------------------------ */
/*  getPetById                                                   */
/* ------------------------------------------------------------------ */
void PetApiImpl::get_pet_by_id(
    const std::int64_t &path_petId
    , 
    getPetByIdResponse &response)
{
    /* TODO: business logic.                                             *
     * Replace the placeholder below with real handling.                 */

    response = std::integral_constant<
        drogon::HttpStatusCode,
        drogon::k501NotImplemented>{};
}
/* ------------------------------------------------------------------ */
/*  updatePet                                                   */
/* ------------------------------------------------------------------ */
void PetApiImpl::update_pet(
    const Pet &pet
    , 
    updatePetResponse &response)
{
    /* TODO: business logic.                                             *
     * Replace the placeholder below with real handling.                 */

    response = std::integral_constant<
        drogon::HttpStatusCode,
        drogon::k501NotImplemented>{};
}
/* ------------------------------------------------------------------ */
/*  updatePetWithForm                                                   */
/* ------------------------------------------------------------------ */
void PetApiImpl::update_pet_with_form(
    const std::int64_t &path_petId, 
        const std::string &name, 
        const std::string &status
    , 
    updatePetWithFormResponse &response)
{
    /* TODO: business logic.                                             *
     * Replace the placeholder below with real handling.                 */

    response = std::integral_constant<
        drogon::HttpStatusCode,
        drogon::k501NotImplemented>{};
}
/* ------------------------------------------------------------------ */
/*  uploadFile                                                   */
/* ------------------------------------------------------------------ */
void PetApiImpl::upload_file(
    const std::int64_t &path_petId, 
        const std::string &additionalMetadata, 
        const std::string &file
    , 
    uploadFileResponse &response)
{
    /* TODO: business logic.                                             *
     * Replace the placeholder below with real handling.                 */

    response = std::integral_constant<
        drogon::HttpStatusCode,
        drogon::k501NotImplemented>{};
}

} /* namespace org::openapitools::server::api */

