/**
* OpenAPI Petstore
* This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
    #include "PetApi.h"
    #include "Helpers.h"
    #include <json/json.h>

    namespace org::openapitools::server::api
    {

    using namespace org::openapitools::server::helpers;
        using namespace org::openapitools::server::model;

    const std::string PetApi::base = "/v2";

    /* ----------------------------------------------------------------------
    *  Generic helpers
    * -------------------------------------------------------------------- */
    void PetApi::handleParsingException(
    const std::exception& ex,
    std::function<void (const drogon::HttpResponsePtr &)>&& cb) const noexcept
        {
        auto [status, body] = handleParsingException(ex);
        auto resp           = drogon::HttpResponse::newHttpResponse(body);
        resp->setStatusCode(status);
        cb(resp);
        }

        std::pair<drogon::HttpStatusCode, std::string>
    PetApi::handleParsingException(const std::exception& ex) const noexcept
        {
        try { throw; }
        catch (Json::Exception&     e) { return {drogon::k400BadRequest, e.what()}; }
        catch (ValidationException& e) { return {drogon::k400BadRequest, e.what()}; }
        catch (std::exception&      e) { return {drogon::k500InternalServerError, e.what()}; }
        }

        void PetApi::handleOperationException(
        const std::exception& ex,
        std::function<void (const drogon::HttpResponsePtr &)>&& cb) const noexcept
        {
        auto [status, body] = handleOperationException(ex);
        auto resp           = drogon::HttpResponse::newHttpResponse(body);
        resp->setStatusCode(status);
        cb(resp);
        }

        std::pair<drogon::HttpStatusCode, std::string>
    PetApi::handleOperationException(const std::exception& ex) const noexcept
        {
        return {drogon::k500InternalServerError, ex.what()};
        }

        /* ----------------------------------------------------------------------
        *  One method per operation
        * -------------------------------------------------------------------- */
            /* ---------- addPet ---------- */
            void PetApi::add_pet_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& cb)
            {
            try {
                /* -------- parameter extraction -------- */
                        Pet pet;
                            try {
                            Json::Value jsonBody;
                            Json::Reader reader;
                            if (!reader.parse(req->getBody(), jsonBody))
                            throw std::invalid_argument("Invalid JSON body");
                            from_json(jsonBody, pet);
                        pet.validate();
                            } catch (const std::exception& e) {
                            handleParsingException(e, std::move(cb));
                            return;
                            }



                /* -------- delegate to service -------- */
            addPetResponse respVariant;
                service->add_pet(
            pet
                respVariant);

                /* -------- serialize & return -------- */
                auto resp = org::openapitools::server::helpers::variantToHttp(respVariant);
                cb(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            cb(resp);
            }
            }
            /* ---------- deletePet ---------- */
            void PetApi::delete_pet_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& cb,
            const std::int64_t& path_petId)
            {
            try {
                /* -------- parameter extraction -------- */


                        std::string header_apiKey = req->getHeader("api_key");
                        
                        
                        
                          std::string  apiKey = header_apiKey; 

                /* -------- delegate to service -------- */
            deletePetResponse respVariant;
                service->delete_pet(
            path_petId, header_apiKey
                respVariant);

                /* -------- serialize & return -------- */
                auto resp = org::openapitools::server::helpers::variantToHttp(respVariant);
                cb(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            cb(resp);
            }
            }
            /* ---------- findPetsByStatus ---------- */
            void PetApi::find_pets_by_status_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& cb,
            const std::optional<std::vector<std::string>>& query_status)
            {
            try {
                /* -------- parameter extraction -------- */

                        {
                        auto _q = req->getParameter("status");
                        std::optional<std::vector<std::string>> status;
                        if (!_q.empty()) {
                    std::vector<std::string> tmp;
                        if (fromStringValue(_q, tmp))
                    status = tmp;
                        }
                        }


                /* -------- delegate to service -------- */
            findPetsByStatusResponse respVariant;
                service->find_pets_by_status(
            query_status
                respVariant);

                /* -------- serialize & return -------- */
                auto resp = org::openapitools::server::helpers::variantToHttp(respVariant);
                cb(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            cb(resp);
            }
            }
            /* ---------- findPetsByTags ---------- */
            void PetApi::find_pets_by_tags_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& cb,
            const std::optional<std::vector<std::string>>& query_tags)
            {
            try {
                /* -------- parameter extraction -------- */

                        {
                        auto _q = req->getParameter("tags");
                        std::optional<std::vector<std::string>> tags;
                        if (!_q.empty()) {
                    std::vector<std::string> tmp;
                        if (fromStringValue(_q, tmp))
                    tags = tmp;
                        }
                        }


                /* -------- delegate to service -------- */
            findPetsByTagsResponse respVariant;
                service->find_pets_by_tags(
            query_tags
                respVariant);

                /* -------- serialize & return -------- */
                auto resp = org::openapitools::server::helpers::variantToHttp(respVariant);
                cb(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            cb(resp);
            }
            }
            /* ---------- getPetById ---------- */
            void PetApi::get_pet_by_id_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& cb,
            const std::int64_t& path_petId)
            {
            try {
                /* -------- parameter extraction -------- */



                /* -------- delegate to service -------- */
            getPetByIdResponse respVariant;
                service->get_pet_by_id(
            path_petId
                respVariant);

                /* -------- serialize & return -------- */
                auto resp = org::openapitools::server::helpers::variantToHttp(respVariant);
                cb(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            cb(resp);
            }
            }
            /* ---------- updatePet ---------- */
            void PetApi::update_pet_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& cb)
            {
            try {
                /* -------- parameter extraction -------- */
                        Pet pet;
                            try {
                            Json::Value jsonBody;
                            Json::Reader reader;
                            if (!reader.parse(req->getBody(), jsonBody))
                            throw std::invalid_argument("Invalid JSON body");
                            from_json(jsonBody, pet);
                        pet.validate();
                            } catch (const std::exception& e) {
                            handleParsingException(e, std::move(cb));
                            return;
                            }



                /* -------- delegate to service -------- */
            updatePetResponse respVariant;
                service->update_pet(
            pet
                respVariant);

                /* -------- serialize & return -------- */
                auto resp = org::openapitools::server::helpers::variantToHttp(respVariant);
                cb(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            cb(resp);
            }
            }
            /* ---------- updatePetWithForm ---------- */
            void PetApi::update_pet_with_form_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& cb,
            const std::int64_t& path_petId,
            const std::string& name,
            const std::string& status)
            {
            try {

                /* Fallback: give raw request to service */
            updatePetWithFormResponse respVariant;
                service->update_pet_with_form(req, std::move(cb), respVariant);

            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            cb(resp);
            }
            }
            /* ---------- uploadFile ---------- */
            void PetApi::upload_file_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& cb,
            const std::int64_t& path_petId,
            const std::string& additionalMetadata,
            const std::string& file)
            {
            try {

                /* Fallback: give raw request to service */
            uploadFileResponse respVariant;
                service->upload_file(req, std::move(cb), respVariant);

            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            cb(resp);
            }
            }

        void PetApi::pet_api_default_handler(
        const drogon::HttpRequestPtr& /*req*/,
        std::function<void (const drogon::HttpResponsePtr &)>&& cb)
        {
        auto resp = drogon::HttpResponse::newHttpResponse("The requested method does not exist");
        resp->setStatusCode(drogon::k404NotFound);
        cb(resp);
        }

        } // namespace org::openapitools::server::api

