/**
* OpenAPI Petstore
* This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
* PetApi.h
*
* 
*/
#ifndef PetApi_H_
#define PetApi_H_



#include <drogon/HttpController.h>
#include "PetApiInterface.h"

#include <optional>
    #include <utility>

#include "ApiResponse.h"
#include "Pet.h"
#include <string>
#include <vector>

    namespace org::openapitools::server::api
    {

    class  PetApi : public drogon::HttpController<PetApi, false>
    {
    private:
    /* ---------- Route table ---------- */
    METHOD_LIST_BEGIN
        ADD_METHOD_TO(PetApi::add_pet_handler, base + "/pet", "Post");
        ADD_METHOD_TO(PetApi::delete_pet_handler, base + "/pet/{1}", "Delete");
        ADD_METHOD_TO(PetApi::find_pets_by_status_handler, base + "/pet/findByStatus?status={1}", "Get");
        ADD_METHOD_TO(PetApi::find_pets_by_tags_handler, base + "/pet/findByTags?tags={1}", "Get");
        ADD_METHOD_TO(PetApi::get_pet_by_id_handler, base + "/pet/{1}", "Get");
        ADD_METHOD_TO(PetApi::update_pet_handler, base + "/pet", "Put");
        ADD_METHOD_TO(PetApi::update_pet_with_form_handler, base + "/pet/{1}", "Post");
        ADD_METHOD_TO(PetApi::upload_file_handler, base + "/pet/{1}/uploadImage", "Post");
    METHOD_LIST_END

    public:
    /* ---------- Handler prototypes ---------- */
        void add_pet_handler(const drogon::HttpRequestPtr& req,
        std::function<void (const drogon::HttpResponsePtr &)>&& callback);
        void delete_pet_handler(const drogon::HttpRequestPtr& req,
        std::function<void (const drogon::HttpResponsePtr &)>&& callback, const std::int64_t& path_petId);
        void find_pets_by_status_handler(const drogon::HttpRequestPtr& req,
        std::function<void (const drogon::HttpResponsePtr &)>&& callback, const std::optional<std::vector<std::string>>& query_status);
        void find_pets_by_tags_handler(const drogon::HttpRequestPtr& req,
        std::function<void (const drogon::HttpResponsePtr &)>&& callback, const std::optional<std::vector<std::string>>& query_tags);
        void get_pet_by_id_handler(const drogon::HttpRequestPtr& req,
        std::function<void (const drogon::HttpResponsePtr &)>&& callback, const std::int64_t& path_petId);
        void update_pet_handler(const drogon::HttpRequestPtr& req,
        std::function<void (const drogon::HttpResponsePtr &)>&& callback);
        void update_pet_with_form_handler(const drogon::HttpRequestPtr& req,
        std::function<void (const drogon::HttpResponsePtr &)>&& callback, const std::int64_t& path_petId, const std::string& name, const std::string& status);
        void upload_file_handler(const drogon::HttpRequestPtr& req,
        std::function<void (const drogon::HttpResponsePtr &)>&& callback, const std::int64_t& path_petId, const std::string& additionalMetadata, const std::string& file);

    /* Fallback for unmatched routes */
    void pet_api_default_handler(const drogon::HttpRequestPtr& req,
    std::function<void (const drogon::HttpResponsePtr &)>&& callback);

    /* Global prefix (e.g. "/v2") – defined in .cpp */
    static const std::string base;

PetApi() = default;
    explicit PetApi(std::unique_ptr<PetApiInterface> svc)
    : service(std::move(svc)) {}

    private:
    std::unique_ptr<PetApiInterface> service;

    /* ---- error helpers ---- */
    virtual void handleParsingException(const std::exception& ex,
    std::function<void (const drogon::HttpResponsePtr &)>&& callback) const noexcept;

    virtual std::pair<drogon::HttpStatusCode, std::string>
    handleParsingException(const std::exception& ex) const noexcept;

    virtual void handleOperationException(const std::exception& ex,
    std::function<void (const drogon::HttpResponsePtr &)>&& callback) const noexcept;

    virtual std::pair<drogon::HttpStatusCode, std::string>
    handleOperationException(const std::exception& ex) const noexcept;
    };

    } // namespace org::openapitools::server::api

    #endif /* PetApi_H_ */

