/**
* OpenAPI Petstore
* This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

    #include "PetApi.h"
    #include "Helpers.h"
    #include <json/json.h>

    namespace org::openapitools::server::api
    {

    using namespace org::openapitools::server::helpers;
        using namespace org::openapitools::server::model;

    const std::string PetApi::base = "/v2";

    void PetApi::handleParsingException(
    const std::exception& ex,
    std::function<void (const drogon::HttpResponsePtr &)>&& callback) const noexcept
        {
        auto [status, body] = handleParsingException(ex);
        auto resp          = drogon::HttpResponse::newHttpResponse(body);
        resp->setStatusCode(status);
        callback(resp);
        }

        std::pair<drogon::HttpStatusCode, std::string>
    PetApi::handleParsingException(const std::exception& ex) const noexcept
        {
        try { throw; }
        catch (Json::Exception&               e) { return {drogon::k400BadRequest, e.what()}; }
        catch (ValidationException&           e) { return {drogon::k400BadRequest, e.what()}; }
        catch (std::exception&                e) { return {drogon::k500InternalServerError, e.what()}; }
        }

        void PetApi::handleOperationException(
        const std::exception& ex,
        std::function<void (const drogon::HttpResponsePtr &)>&& callback) const noexcept
        {
        auto [status, body] = handleOperationException(ex);
        auto resp          = drogon::HttpResponse::newHttpResponse(body);
        resp->setStatusCode(status);
        callback(resp);
        }

        std::pair<drogon::HttpStatusCode, std::string>
    PetApi::handleOperationException(const std::exception& ex) const noexcept
        {
        return {drogon::k500InternalServerError, ex.what()};
        }

            /* ---------- addPet ---------- */
            void PetApi::add_pet_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& callback)
            {
            try {
                /* --------‑‑‑ parameter extraction ‑‑‑--------- */

                    // Body parameter
                        Pet pet;
                            try {
                            Json::Value jsonBody;
                            Json::Reader reader;
                            if (!reader.parse(req->getBody(), jsonBody))
                            throw std::invalid_argument("Invalid JSON body");
                            from_json(jsonBody, pet);
                        pet.validate();
                            } catch (const std::exception& e) {
                            handleParsingException(e, std::move(callback));
                            return;
                            }


                /* ---------- call service ---------- */
            addPetResponse response;
                service->add_pet(
            pet, response);

                /* ---------- serialize & return ---------- */
                // You can convert `response` (std::variant) to HttpResponse here.
                // For now just return 501.
                auto resp = drogon::HttpResponse::newHttpResponse("Not implemented");
                resp->setStatusCode(drogon::k501NotImplemented);
                callback(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            callback(resp);
            }
            }
            /* ---------- deletePet ---------- */
            void PetApi::delete_pet_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& callback,
            const std::int64_t& path_petId)
            {
            try {
                /* --------‑‑‑ parameter extraction ‑‑‑--------- */
                    // Path parameters
                        // auto petId = /* extract from route */ ;



                    // Header parameters
                        std::string header_apiKey = req->getHeader("api_key");
                        
                        
                        
                          std::string  apiKey = header_apiKey; 
                /* ---------- call service ---------- */
            deletePetResponse response;
                service->delete_pet(
            path_petId, header_apiKey, response);

                /* ---------- serialize & return ---------- */
                // You can convert `response` (std::variant) to HttpResponse here.
                // For now just return 501.
                auto resp = drogon::HttpResponse::newHttpResponse("Not implemented");
                resp->setStatusCode(drogon::k501NotImplemented);
                callback(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            callback(resp);
            }
            }
            /* ---------- findPetsByStatus ---------- */
            void PetApi::find_pets_by_status_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& callback,
            const std::optional<std::vector<std::string>>& query_status)
            {
            try {
                /* --------‑‑‑ parameter extraction ‑‑‑--------- */


                    // Query parameters
                        {   /* status */
                        auto _q = req->getParameter("status");
                        std::optional<std::vector<std::string>> status;
                        if (!_q.empty()) {
                    std::vector<std::string> tmp;
                        if (fromStringValue(_q, tmp))
                    status = tmp;
                        }
                        }

                /* ---------- call service ---------- */
            findPetsByStatusResponse response;
                service->find_pets_by_status(
            query_status, response);

                /* ---------- serialize & return ---------- */
                // You can convert `response` (std::variant) to HttpResponse here.
                // For now just return 501.
                auto resp = drogon::HttpResponse::newHttpResponse("Not implemented");
                resp->setStatusCode(drogon::k501NotImplemented);
                callback(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            callback(resp);
            }
            }
            /* ---------- findPetsByTags ---------- */
            void PetApi::find_pets_by_tags_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& callback,
            const std::optional<std::vector<std::string>>& query_tags)
            {
            try {
                /* --------‑‑‑ parameter extraction ‑‑‑--------- */


                    // Query parameters
                        {   /* tags */
                        auto _q = req->getParameter("tags");
                        std::optional<std::vector<std::string>> tags;
                        if (!_q.empty()) {
                    std::vector<std::string> tmp;
                        if (fromStringValue(_q, tmp))
                    tags = tmp;
                        }
                        }

                /* ---------- call service ---------- */
            findPetsByTagsResponse response;
                service->find_pets_by_tags(
            query_tags, response);

                /* ---------- serialize & return ---------- */
                // You can convert `response` (std::variant) to HttpResponse here.
                // For now just return 501.
                auto resp = drogon::HttpResponse::newHttpResponse("Not implemented");
                resp->setStatusCode(drogon::k501NotImplemented);
                callback(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            callback(resp);
            }
            }
            /* ---------- getPetById ---------- */
            void PetApi::get_pet_by_id_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& callback,
            const std::int64_t& path_petId)
            {
            try {
                /* --------‑‑‑ parameter extraction ‑‑‑--------- */
                    // Path parameters
                        // auto petId = /* extract from route */ ;



                /* ---------- call service ---------- */
            getPetByIdResponse response;
                service->get_pet_by_id(
            path_petId, response);

                /* ---------- serialize & return ---------- */
                // You can convert `response` (std::variant) to HttpResponse here.
                // For now just return 501.
                auto resp = drogon::HttpResponse::newHttpResponse("Not implemented");
                resp->setStatusCode(drogon::k501NotImplemented);
                callback(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            callback(resp);
            }
            }
            /* ---------- updatePet ---------- */
            void PetApi::update_pet_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& callback)
            {
            try {
                /* --------‑‑‑ parameter extraction ‑‑‑--------- */

                    // Body parameter
                        Pet pet;
                            try {
                            Json::Value jsonBody;
                            Json::Reader reader;
                            if (!reader.parse(req->getBody(), jsonBody))
                            throw std::invalid_argument("Invalid JSON body");
                            from_json(jsonBody, pet);
                        pet.validate();
                            } catch (const std::exception& e) {
                            handleParsingException(e, std::move(callback));
                            return;
                            }


                /* ---------- call service ---------- */
            updatePetResponse response;
                service->update_pet(
            pet, response);

                /* ---------- serialize & return ---------- */
                // You can convert `response` (std::variant) to HttpResponse here.
                // For now just return 501.
                auto resp = drogon::HttpResponse::newHttpResponse("Not implemented");
                resp->setStatusCode(drogon::k501NotImplemented);
                callback(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            callback(resp);
            }
            }
            /* ---------- updatePetWithForm ---------- */
            void PetApi::update_pet_with_form_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& callback,
            const std::int64_t& path_petId,
            const std::string& name,
            const std::string& status)
            {
            try {
                /* Fallback: give raw request to service */
            updatePetWithFormResponse response;
                service->update_pet_with_form(req, std::move(callback), response);

            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            callback(resp);
            }
            }
            /* ---------- uploadFile ---------- */
            void PetApi::upload_file_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& callback,
            const std::int64_t& path_petId,
            const std::string& additionalMetadata,
            const std::string& file)
            {
            try {
                /* Fallback: give raw request to service */
            uploadFileResponse response;
                service->upload_file(req, std::move(callback), response);

            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            callback(resp);
            }
            }

        void PetApi::pet_api_default_handler(
        const drogon::HttpRequestPtr&               /*req*/,
        std::function<void (const drogon::HttpResponsePtr &)>&& callback)
        {
        auto resp = drogon::HttpResponse::newHttpResponse("The requested method does not exist");
        resp->setStatusCode(drogon::k404NotFound);
        callback(resp);
        }

        } // namespace org::openapitools::server::api

