/**
* OpenAPI Petstore
* This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
 * PetApiImpl.h  –  concrete implementation of PetApiInterface
 *
 * 
 */
#ifndef PET_API_IMPL_H_
#define PET_API_IMPL_H_

/* ----------------------------------------------------------------------
 *  Includes
 * -------------------------------------------------------------------- */

#include <drogon/HttpTypes.h>
#include <memory>
#include <optional>

#include "PetApiInterface.h"    /* generated abstract interface */

#include "ApiResponse.h"
#include "Pet.h"
#include <string>
#include <vector>

namespace org::openapitools::server::api
{

using namespace org::openapitools::server::model;     /* DTO namespace (optional) */

/* ======================================================================
 *  Concrete service class
 * ==================================================================== */
class  PetApiImpl final : public PetApiInterface
{
public:
    PetApiImpl()  = default;
    ~PetApiImpl() override = default;

    /* ------------- addPet ------------- */
    void add_pet(
        const Pet &pet
        , 
        addPetResponse &response
    ) override;
    /* ------------- deletePet ------------- */
    void delete_pet(
        const std::int64_t &path_petId, 
                const std::string &header_apiKey
        , 
        deletePetResponse &response
    ) override;
    /* ------------- findPetsByStatus ------------- */
    void find_pets_by_status(
        const std::optional<std::vector<std::string>> &query_status
        , 
        findPetsByStatusResponse &response
    ) override;
    /* ------------- findPetsByTags ------------- */
    void find_pets_by_tags(
        const std::optional<std::vector<std::string>> &query_tags
        , 
        findPetsByTagsResponse &response
    ) override;
    /* ------------- getPetById ------------- */
    void get_pet_by_id(
        const std::int64_t &path_petId
        , 
        getPetByIdResponse &response
    ) override;
    /* ------------- updatePet ------------- */
    void update_pet(
        const Pet &pet
        , 
        updatePetResponse &response
    ) override;
    /* ------------- updatePetWithForm ------------- */
    void update_pet_with_form(
        const std::int64_t &path_petId, 
                const std::string &name, 
                const std::string &status
        , 
        updatePetWithFormResponse &response
    ) override;
    /* ------------- uploadFile ------------- */
    void upload_file(
        const std::int64_t &path_petId, 
                const std::string &additionalMetadata, 
                const std::string &file
        , 
        uploadFileResponse &response
    ) override;
};

} /* namespace org::openapitools::server::api */

#endif /* _IMPL_H_ */
