/**
* OpenAPI Petstore
* This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
    #include "StoreApi.h"
    #include "Helpers.h"
    #include <json/json.h>

    namespace org::openapitools::server::api
    {

    using namespace org::openapitools::server::helpers;
        using namespace org::openapitools::server::model;

    const std::string StoreApi::base = "/v2";

    /* ----------------------------------------------------------------------
    *  Generic helpers
    * -------------------------------------------------------------------- */
    void StoreApi::handleParsingException(
    const std::exception& ex,
    std::function<void (const drogon::HttpResponsePtr &)>&& cb) const noexcept
        {
        auto [status, body] = handleParsingException(ex);
        auto resp           = drogon::HttpResponse::newHttpResponse(body);
        resp->setStatusCode(status);
        cb(resp);
        }

        std::pair<drogon::HttpStatusCode, std::string>
    StoreApi::handleParsingException(const std::exception& ex) const noexcept
        {
        try { throw; }
        catch (Json::Exception&     e) { return {drogon::k400BadRequest, e.what()}; }
        catch (ValidationException& e) { return {drogon::k400BadRequest, e.what()}; }
        catch (std::exception&      e) { return {drogon::k500InternalServerError, e.what()}; }
        }

        void StoreApi::handleOperationException(
        const std::exception& ex,
        std::function<void (const drogon::HttpResponsePtr &)>&& cb) const noexcept
        {
        auto [status, body] = handleOperationException(ex);
        auto resp           = drogon::HttpResponse::newHttpResponse(body);
        resp->setStatusCode(status);
        cb(resp);
        }

        std::pair<drogon::HttpStatusCode, std::string>
    StoreApi::handleOperationException(const std::exception& ex) const noexcept
        {
        return {drogon::k500InternalServerError, ex.what()};
        }

        /* ----------------------------------------------------------------------
        *  One method per operation
        * -------------------------------------------------------------------- */
            /* ---------- deleteOrder ---------- */
            void StoreApi::delete_order_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& cb,
            const std::string& path_orderId)
            {
            try {
                /* -------- parameter extraction -------- */



                /* -------- delegate to service -------- */
            deleteOrderResponse respVariant;
                service->delete_order(
            path_orderId
                respVariant);

                /* -------- serialize & return -------- */
                auto resp = org::openapitools::server::helpers::variantToHttp(respVariant);
                cb(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            cb(resp);
            }
            }
            /* ---------- getInventory ---------- */
            void StoreApi::get_inventory_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& cb)
            {
            try {
                /* -------- parameter extraction -------- */



                /* -------- delegate to service -------- */
            getInventoryResponse respVariant;
                service->get_inventory(
            
                respVariant);

                /* -------- serialize & return -------- */
                auto resp = org::openapitools::server::helpers::variantToHttp(respVariant);
                cb(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            cb(resp);
            }
            }
            /* ---------- getOrderById ---------- */
            void StoreApi::get_order_by_id_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& cb,
            const std::int64_t& path_orderId)
            {
            try {
                /* -------- parameter extraction -------- */



                /* -------- delegate to service -------- */
            getOrderByIdResponse respVariant;
                service->get_order_by_id(
            path_orderId
                respVariant);

                /* -------- serialize & return -------- */
                auto resp = org::openapitools::server::helpers::variantToHttp(respVariant);
                cb(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            cb(resp);
            }
            }
            /* ---------- placeOrder ---------- */
            void StoreApi::place_order_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& cb)
            {
            try {
                /* -------- parameter extraction -------- */
                        Order order;
                            try {
                            Json::Value jsonBody;
                            Json::Reader reader;
                            if (!reader.parse(req->getBody(), jsonBody))
                            throw std::invalid_argument("Invalid JSON body");
                            from_json(jsonBody, order);
                        order.validate();
                            } catch (const std::exception& e) {
                            handleParsingException(e, std::move(cb));
                            return;
                            }



                /* -------- delegate to service -------- */
            placeOrderResponse respVariant;
                service->place_order(
            order
                respVariant);

                /* -------- serialize & return -------- */
                auto resp = org::openapitools::server::helpers::variantToHttp(respVariant);
                cb(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            cb(resp);
            }
            }

        void StoreApi::store_api_default_handler(
        const drogon::HttpRequestPtr& /*req*/,
        std::function<void (const drogon::HttpResponsePtr &)>&& cb)
        {
        auto resp = drogon::HttpResponse::newHttpResponse("The requested method does not exist");
        resp->setStatusCode(drogon::k404NotFound);
        cb(resp);
        }

        } // namespace org::openapitools::server::api

