/**
* OpenAPI Petstore
* This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

    #include "StoreApi.h"
    #include "Helpers.h"
    #include <json/json.h>

    namespace org::openapitools::server::api
    {

    using namespace org::openapitools::server::helpers;
        using namespace org::openapitools::server::model;

    const std::string StoreApi::base = "/v2";

    void StoreApi::handleParsingException(
    const std::exception& ex,
    std::function<void (const drogon::HttpResponsePtr &)>&& callback) const noexcept
        {
        auto [status, body] = handleParsingException(ex);
        auto resp          = drogon::HttpResponse::newHttpResponse(body);
        resp->setStatusCode(status);
        callback(resp);
        }

        std::pair<drogon::HttpStatusCode, std::string>
    StoreApi::handleParsingException(const std::exception& ex) const noexcept
        {
        try { throw; }
        catch (Json::Exception&               e) { return {drogon::k400BadRequest, e.what()}; }
        catch (ValidationException&           e) { return {drogon::k400BadRequest, e.what()}; }
        catch (std::exception&                e) { return {drogon::k500InternalServerError, e.what()}; }
        }

        void StoreApi::handleOperationException(
        const std::exception& ex,
        std::function<void (const drogon::HttpResponsePtr &)>&& callback) const noexcept
        {
        auto [status, body] = handleOperationException(ex);
        auto resp          = drogon::HttpResponse::newHttpResponse(body);
        resp->setStatusCode(status);
        callback(resp);
        }

        std::pair<drogon::HttpStatusCode, std::string>
    StoreApi::handleOperationException(const std::exception& ex) const noexcept
        {
        return {drogon::k500InternalServerError, ex.what()};
        }

            /* ---------- deleteOrder ---------- */
            void StoreApi::delete_order_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& callback,
            const std::string& path_orderId)
            {
            try {
                /* --------‑‑‑ parameter extraction ‑‑‑--------- */
                    // Path parameters
                        // auto orderId = /* extract from route */ ;



                /* ---------- call service ---------- */
            deleteOrderResponse response;
                service->delete_order(
            path_orderId, response);

                /* ---------- serialize & return ---------- */
                // You can convert `response` (std::variant) to HttpResponse here.
                // For now just return 501.
                auto resp = drogon::HttpResponse::newHttpResponse("Not implemented");
                resp->setStatusCode(drogon::k501NotImplemented);
                callback(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            callback(resp);
            }
            }
            /* ---------- getInventory ---------- */
            void StoreApi::get_inventory_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& callback)
            {
            try {
                /* --------‑‑‑ parameter extraction ‑‑‑--------- */



                /* ---------- call service ---------- */
            getInventoryResponse response;
                service->get_inventory(
            response);

                /* ---------- serialize & return ---------- */
                // You can convert `response` (std::variant) to HttpResponse here.
                // For now just return 501.
                auto resp = drogon::HttpResponse::newHttpResponse("Not implemented");
                resp->setStatusCode(drogon::k501NotImplemented);
                callback(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            callback(resp);
            }
            }
            /* ---------- getOrderById ---------- */
            void StoreApi::get_order_by_id_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& callback,
            const std::int64_t& path_orderId)
            {
            try {
                /* --------‑‑‑ parameter extraction ‑‑‑--------- */
                    // Path parameters
                        // auto orderId = /* extract from route */ ;



                /* ---------- call service ---------- */
            getOrderByIdResponse response;
                service->get_order_by_id(
            path_orderId, response);

                /* ---------- serialize & return ---------- */
                // You can convert `response` (std::variant) to HttpResponse here.
                // For now just return 501.
                auto resp = drogon::HttpResponse::newHttpResponse("Not implemented");
                resp->setStatusCode(drogon::k501NotImplemented);
                callback(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            callback(resp);
            }
            }
            /* ---------- placeOrder ---------- */
            void StoreApi::place_order_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& callback)
            {
            try {
                /* --------‑‑‑ parameter extraction ‑‑‑--------- */

                    // Body parameter
                        Order order;
                            try {
                            Json::Value jsonBody;
                            Json::Reader reader;
                            if (!reader.parse(req->getBody(), jsonBody))
                            throw std::invalid_argument("Invalid JSON body");
                            from_json(jsonBody, order);
                        order.validate();
                            } catch (const std::exception& e) {
                            handleParsingException(e, std::move(callback));
                            return;
                            }


                /* ---------- call service ---------- */
            placeOrderResponse response;
                service->place_order(
            order, response);

                /* ---------- serialize & return ---------- */
                // You can convert `response` (std::variant) to HttpResponse here.
                // For now just return 501.
                auto resp = drogon::HttpResponse::newHttpResponse("Not implemented");
                resp->setStatusCode(drogon::k501NotImplemented);
                callback(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            callback(resp);
            }
            }

        void StoreApi::store_api_default_handler(
        const drogon::HttpRequestPtr&               /*req*/,
        std::function<void (const drogon::HttpResponsePtr &)>&& callback)
        {
        auto resp = drogon::HttpResponse::newHttpResponse("The requested method does not exist");
        resp->setStatusCode(drogon::k404NotFound);
        callback(resp);
        }

        } // namespace org::openapitools::server::api

