/**
* OpenAPI Petstore
* This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
* StoreApi.h
*
* 
*/
#ifndef StoreApi_H_
#define StoreApi_H_



#include <drogon/HttpController.h>
#include "StoreApiInterface.h"

#include <optional>
    #include <utility>

#include "Order.h"
#include <map>
#include <string>

    namespace org::openapitools::server::api
    {

    class  StoreApi : public drogon::HttpController<StoreApi, false>
    {
    private:
    /* ---------- Route table ---------- */
    METHOD_LIST_BEGIN
        ADD_METHOD_TO(StoreApi::delete_order_handler, base + "/store/order/{1}", "Delete");
        ADD_METHOD_TO(StoreApi::get_inventory_handler, base + "/store/inventory", "Get");
        ADD_METHOD_TO(StoreApi::get_order_by_id_handler, base + "/store/order/{1}", "Get");
        ADD_METHOD_TO(StoreApi::place_order_handler, base + "/store/order", "Post");
    METHOD_LIST_END

    public:
    /* ---------- Handler prototypes ---------- */
        void delete_order_handler(const drogon::HttpRequestPtr& req,
        std::function<void (const drogon::HttpResponsePtr &)>&& callback, const std::string& path_orderId);
        void get_inventory_handler(const drogon::HttpRequestPtr& req,
        std::function<void (const drogon::HttpResponsePtr &)>&& callback);
        void get_order_by_id_handler(const drogon::HttpRequestPtr& req,
        std::function<void (const drogon::HttpResponsePtr &)>&& callback, const std::int64_t& path_orderId);
        void place_order_handler(const drogon::HttpRequestPtr& req,
        std::function<void (const drogon::HttpResponsePtr &)>&& callback);

    /* Fallback for unmatched routes */
    void store_api_default_handler(const drogon::HttpRequestPtr& req,
    std::function<void (const drogon::HttpResponsePtr &)>&& callback);

    /* Global prefix (e.g. "/v2") – defined in .cpp */
    static const std::string base;

StoreApi() = default;
    explicit StoreApi(std::unique_ptr<StoreApiInterface> svc)
    : service(std::move(svc)) {}

    private:
    std::unique_ptr<StoreApiInterface> service;

    /* ---- error helpers ---- */
    virtual void handleParsingException(const std::exception& ex,
    std::function<void (const drogon::HttpResponsePtr &)>&& callback) const noexcept;

    virtual std::pair<drogon::HttpStatusCode, std::string>
    handleParsingException(const std::exception& ex) const noexcept;

    virtual void handleOperationException(const std::exception& ex,
    std::function<void (const drogon::HttpResponsePtr &)>&& callback) const noexcept;

    virtual std::pair<drogon::HttpStatusCode, std::string>
    handleOperationException(const std::exception& ex) const noexcept;
    };

    } // namespace org::openapitools::server::api

    #endif /* StoreApi_H_ */

