/**
* OpenAPI Petstore
* This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
 * StoreApiImpl.h  –  concrete implementation of StoreApiInterface
 *
 * 
 */
#ifndef STORE_API_IMPL_H_
#define STORE_API_IMPL_H_

/* ----------------------------------------------------------------------
 *  Includes
 * -------------------------------------------------------------------- */

#include <drogon/HttpTypes.h>
#include <memory>
#include <optional>

#include "StoreApiInterface.h"    /* generated abstract interface */

#include "Order.h"
#include <map>
#include <string>

namespace org::openapitools::server::api
{

using namespace org::openapitools::server::model;     /* DTO namespace (optional) */

/* ======================================================================
 *  Concrete service class
 * ==================================================================== */
class  StoreApiImpl final : public StoreApiInterface
{
public:
    StoreApiImpl()  = default;
    ~StoreApiImpl() override = default;

    /* ------------- deleteOrder ------------- */
    void delete_order(
        const std::string &path_orderId
        , 
        deleteOrderResponse &response
    ) override;
    /* ------------- getInventory ------------- */
    void get_inventory(

        getInventoryResponse &response
    ) override;
    /* ------------- getOrderById ------------- */
    void get_order_by_id(
        const std::int64_t &path_orderId
        , 
        getOrderByIdResponse &response
    ) override;
    /* ------------- placeOrder ------------- */
    void place_order(
        const Order &order
        , 
        placeOrderResponse &response
    ) override;
};

} /* namespace org::openapitools::server::api */

#endif /* _IMPL_H_ */
