/**
* OpenAPI Petstore
* This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "StoreApiImpl.h"

namespace org::openapitools::server::api
{

/* ------------------------------------------------------------------ */
/*  deleteOrder                                                   */
/* ------------------------------------------------------------------ */
void StoreApiImpl::delete_order(
    const std::string &path_orderId
    , 
    deleteOrderResponse &response)
{
    /* TODO: business logic.                                             *
     * Replace the placeholder below with real handling.                 */

    response = std::integral_constant<
        drogon::HttpStatusCode,
        drogon::k501NotImplemented>{};
}
/* ------------------------------------------------------------------ */
/*  getInventory                                                   */
/* ------------------------------------------------------------------ */
void StoreApiImpl::get_inventory(

    getInventoryResponse &response)
{
    /* TODO: business logic.                                             *
     * Replace the placeholder below with real handling.                 */

    response = std::integral_constant<
        drogon::HttpStatusCode,
        drogon::k501NotImplemented>{};
}
/* ------------------------------------------------------------------ */
/*  getOrderById                                                   */
/* ------------------------------------------------------------------ */
void StoreApiImpl::get_order_by_id(
    const std::int64_t &path_orderId
    , 
    getOrderByIdResponse &response)
{
    /* TODO: business logic.                                             *
     * Replace the placeholder below with real handling.                 */

    response = std::integral_constant<
        drogon::HttpStatusCode,
        drogon::k501NotImplemented>{};
}
/* ------------------------------------------------------------------ */
/*  placeOrder                                                   */
/* ------------------------------------------------------------------ */
void StoreApiImpl::place_order(
    const Order &order
    , 
    placeOrderResponse &response)
{
    /* TODO: business logic.                                             *
     * Replace the placeholder below with real handling.                 */

    response = std::integral_constant<
        drogon::HttpStatusCode,
        drogon::k501NotImplemented>{};
}

} /* namespace org::openapitools::server::api */

