/**
* OpenAPI Petstore
* This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
* UserApi.h
*
* 
*/
#ifndef UserApi_H_
#define UserApi_H_



#include <drogon/HttpController.h>
#include "UserApiInterface.h"

#include <optional>
    #include <utility>

#include "User.h"
#include <string>
#include <vector>

    namespace org::openapitools::server::api
    {

    class  UserApi : public drogon::HttpController<UserApi, false>
    {
    private:
    /* ---------- Route table ---------- */
    METHOD_LIST_BEGIN
        ADD_METHOD_TO(UserApi::create_user_handler, base + "/user", "Post");
        ADD_METHOD_TO(UserApi::create_users_with_array_input_handler, base + "/user/createWithArray", "Post");
        ADD_METHOD_TO(UserApi::create_users_with_list_input_handler, base + "/user/createWithList", "Post");
        ADD_METHOD_TO(UserApi::delete_user_handler, base + "/user/{1}", "Delete");
        ADD_METHOD_TO(UserApi::get_user_by_name_handler, base + "/user/{1}", "Get");
        ADD_METHOD_TO(UserApi::login_user_handler, base + "/user/login?username={1}&password={2}", "Get");
        ADD_METHOD_TO(UserApi::logout_user_handler, base + "/user/logout", "Get");
        ADD_METHOD_TO(UserApi::update_user_handler, base + "/user/{1}", "Put");
    METHOD_LIST_END

    public:
    /* ---------- Handler prototypes ---------- */
        void create_user_handler(const drogon::HttpRequestPtr& req,
        std::function<void (const drogon::HttpResponsePtr &)>&& callback);
        void create_users_with_array_input_handler(const drogon::HttpRequestPtr& req,
        std::function<void (const drogon::HttpResponsePtr &)>&& callback);
        void create_users_with_list_input_handler(const drogon::HttpRequestPtr& req,
        std::function<void (const drogon::HttpResponsePtr &)>&& callback);
        void delete_user_handler(const drogon::HttpRequestPtr& req,
        std::function<void (const drogon::HttpResponsePtr &)>&& callback, const std::string& path_username);
        void get_user_by_name_handler(const drogon::HttpRequestPtr& req,
        std::function<void (const drogon::HttpResponsePtr &)>&& callback, const std::string& path_username);
        void login_user_handler(const drogon::HttpRequestPtr& req,
        std::function<void (const drogon::HttpResponsePtr &)>&& callback, const std::optional<std::string>& query_username, const std::optional<std::string>& query_password);
        void logout_user_handler(const drogon::HttpRequestPtr& req,
        std::function<void (const drogon::HttpResponsePtr &)>&& callback);
        void update_user_handler(const drogon::HttpRequestPtr& req,
        std::function<void (const drogon::HttpResponsePtr &)>&& callback, const std::string& path_username);

    /* Fallback for unmatched routes */
    void user_api_default_handler(const drogon::HttpRequestPtr& req,
    std::function<void (const drogon::HttpResponsePtr &)>&& callback);

    /* Global prefix (e.g. "/v2") – defined in .cpp */
    static const std::string base;

UserApi() = default;
    explicit UserApi(std::unique_ptr<UserApiInterface> svc)
    : service(std::move(svc)) {}

    private:
    std::unique_ptr<UserApiInterface> service;

    /* ---- error helpers ---- */
    virtual void handleParsingException(const std::exception& ex,
    std::function<void (const drogon::HttpResponsePtr &)>&& callback) const noexcept;

    virtual std::pair<drogon::HttpStatusCode, std::string>
    handleParsingException(const std::exception& ex) const noexcept;

    virtual void handleOperationException(const std::exception& ex,
    std::function<void (const drogon::HttpResponsePtr &)>&& callback) const noexcept;

    virtual std::pair<drogon::HttpStatusCode, std::string>
    handleOperationException(const std::exception& ex) const noexcept;
    };

    } // namespace org::openapitools::server::api

    #endif /* UserApi_H_ */

