/**
* OpenAPI Petstore
* This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "UserApiImpl.h"

namespace org::openapitools::server::api
{

/* ------------------------------------------------------------------ */
/*  createUser                                                   */
/* ------------------------------------------------------------------ */
void UserApiImpl::create_user(
    const User &user
    , 
    createUserResponse &response)
{
    /* TODO: business logic.                                             *
     * Replace the placeholder below with real handling.                 */

    response = std::integral_constant<
        drogon::HttpStatusCode,
        drogon::k501NotImplemented>{};
}
/* ------------------------------------------------------------------ */
/*  createUsersWithArrayInput                                                   */
/* ------------------------------------------------------------------ */
void UserApiImpl::create_users_with_array_input(
    const std::vector<org::openapitools::server::model::User> &user
    , 
    createUsersWithArrayInputResponse &response)
{
    /* TODO: business logic.                                             *
     * Replace the placeholder below with real handling.                 */

    response = std::integral_constant<
        drogon::HttpStatusCode,
        drogon::k501NotImplemented>{};
}
/* ------------------------------------------------------------------ */
/*  createUsersWithListInput                                                   */
/* ------------------------------------------------------------------ */
void UserApiImpl::create_users_with_list_input(
    const std::vector<org::openapitools::server::model::User> &user
    , 
    createUsersWithListInputResponse &response)
{
    /* TODO: business logic.                                             *
     * Replace the placeholder below with real handling.                 */

    response = std::integral_constant<
        drogon::HttpStatusCode,
        drogon::k501NotImplemented>{};
}
/* ------------------------------------------------------------------ */
/*  deleteUser                                                   */
/* ------------------------------------------------------------------ */
void UserApiImpl::delete_user(
    const std::string &path_username
    , 
    deleteUserResponse &response)
{
    /* TODO: business logic.                                             *
     * Replace the placeholder below with real handling.                 */

    response = std::integral_constant<
        drogon::HttpStatusCode,
        drogon::k501NotImplemented>{};
}
/* ------------------------------------------------------------------ */
/*  getUserByName                                                   */
/* ------------------------------------------------------------------ */
void UserApiImpl::get_user_by_name(
    const std::string &path_username
    , 
    getUserByNameResponse &response)
{
    /* TODO: business logic.                                             *
     * Replace the placeholder below with real handling.                 */

    response = std::integral_constant<
        drogon::HttpStatusCode,
        drogon::k501NotImplemented>{};
}
/* ------------------------------------------------------------------ */
/*  loginUser                                                   */
/* ------------------------------------------------------------------ */
void UserApiImpl::login_user(
    const std::optional<std::string> &query_username, 
        const std::optional<std::string> &query_password
    , 
    loginUserResponse &response)
{
    /* TODO: business logic.                                             *
     * Replace the placeholder below with real handling.                 */

    response = std::integral_constant<
        drogon::HttpStatusCode,
        drogon::k501NotImplemented>{};
}
/* ------------------------------------------------------------------ */
/*  logoutUser                                                   */
/* ------------------------------------------------------------------ */
void UserApiImpl::logout_user(

    logoutUserResponse &response)
{
    /* TODO: business logic.                                             *
     * Replace the placeholder below with real handling.                 */

    response = std::integral_constant<
        drogon::HttpStatusCode,
        drogon::k501NotImplemented>{};
}
/* ------------------------------------------------------------------ */
/*  updateUser                                                   */
/* ------------------------------------------------------------------ */
void UserApiImpl::update_user(
    const std::string &path_username, 
        const User &user
    , 
    updateUserResponse &response)
{
    /* TODO: business logic.                                             *
     * Replace the placeholder below with real handling.                 */

    response = std::integral_constant<
        drogon::HttpStatusCode,
        drogon::k501NotImplemented>{};
}

} /* namespace org::openapitools::server::api */

