/**
* OpenAPI Petstore
* This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
    #include "UserApi.h"
    #include "Helpers.h"
    #include <json/json.h>

    namespace org::openapitools::server::api
    {

    using namespace org::openapitools::server::helpers;
        using namespace org::openapitools::server::model;

    const std::string UserApi::base = "/v2";

    /* ----------------------------------------------------------------------
    *  Generic helpers
    * -------------------------------------------------------------------- */
    void UserApi::handleParsingException(
    const std::exception& ex,
    std::function<void (const drogon::HttpResponsePtr &)>&& cb) const noexcept
        {
        auto [status, body] = handleParsingException(ex);
        auto resp           = drogon::HttpResponse::newHttpResponse(body);
        resp->setStatusCode(status);
        cb(resp);
        }

        std::pair<drogon::HttpStatusCode, std::string>
    UserApi::handleParsingException(const std::exception& ex) const noexcept
        {
        try { throw; }
        catch (Json::Exception&     e) { return {drogon::k400BadRequest, e.what()}; }
        catch (ValidationException& e) { return {drogon::k400BadRequest, e.what()}; }
        catch (std::exception&      e) { return {drogon::k500InternalServerError, e.what()}; }
        }

        void UserApi::handleOperationException(
        const std::exception& ex,
        std::function<void (const drogon::HttpResponsePtr &)>&& cb) const noexcept
        {
        auto [status, body] = handleOperationException(ex);
        auto resp           = drogon::HttpResponse::newHttpResponse(body);
        resp->setStatusCode(status);
        cb(resp);
        }

        std::pair<drogon::HttpStatusCode, std::string>
    UserApi::handleOperationException(const std::exception& ex) const noexcept
        {
        return {drogon::k500InternalServerError, ex.what()};
        }

        /* ----------------------------------------------------------------------
        *  One method per operation
        * -------------------------------------------------------------------- */
            /* ---------- createUser ---------- */
            void UserApi::create_user_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& cb)
            {
            try {
                /* -------- parameter extraction -------- */
                        User user;
                            try {
                            Json::Value jsonBody;
                            Json::Reader reader;
                            if (!reader.parse(req->getBody(), jsonBody))
                            throw std::invalid_argument("Invalid JSON body");
                            from_json(jsonBody, user);
                        user.validate();
                            } catch (const std::exception& e) {
                            handleParsingException(e, std::move(cb));
                            return;
                            }



                /* -------- delegate to service -------- */
            createUserResponse respVariant;
                service->create_user(
            user
                respVariant);

                /* -------- serialize & return -------- */
                auto resp = org::openapitools::server::helpers::variantToHttp(respVariant);
                cb(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            cb(resp);
            }
            }
            /* ---------- createUsersWithArrayInput ---------- */
            void UserApi::create_users_with_array_input_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& cb)
            {
            try {
                /* -------- parameter extraction -------- */
                        User user;
                            try {
                            Json::Value jsonBody;
                            Json::Reader reader;
                            if (!reader.parse(req->getBody(), jsonBody))
                            throw std::invalid_argument("Invalid JSON body");
                            from_json(jsonBody, user);
                        user.validate();
                            } catch (const std::exception& e) {
                            handleParsingException(e, std::move(cb));
                            return;
                            }



                /* -------- delegate to service -------- */
            createUsersWithArrayInputResponse respVariant;
                service->create_users_with_array_input(
            user
                respVariant);

                /* -------- serialize & return -------- */
                auto resp = org::openapitools::server::helpers::variantToHttp(respVariant);
                cb(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            cb(resp);
            }
            }
            /* ---------- createUsersWithListInput ---------- */
            void UserApi::create_users_with_list_input_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& cb)
            {
            try {
                /* -------- parameter extraction -------- */
                        User user;
                            try {
                            Json::Value jsonBody;
                            Json::Reader reader;
                            if (!reader.parse(req->getBody(), jsonBody))
                            throw std::invalid_argument("Invalid JSON body");
                            from_json(jsonBody, user);
                        user.validate();
                            } catch (const std::exception& e) {
                            handleParsingException(e, std::move(cb));
                            return;
                            }



                /* -------- delegate to service -------- */
            createUsersWithListInputResponse respVariant;
                service->create_users_with_list_input(
            user
                respVariant);

                /* -------- serialize & return -------- */
                auto resp = org::openapitools::server::helpers::variantToHttp(respVariant);
                cb(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            cb(resp);
            }
            }
            /* ---------- deleteUser ---------- */
            void UserApi::delete_user_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& cb,
            const std::string& path_username)
            {
            try {
                /* -------- parameter extraction -------- */



                /* -------- delegate to service -------- */
            deleteUserResponse respVariant;
                service->delete_user(
            path_username
                respVariant);

                /* -------- serialize & return -------- */
                auto resp = org::openapitools::server::helpers::variantToHttp(respVariant);
                cb(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            cb(resp);
            }
            }
            /* ---------- getUserByName ---------- */
            void UserApi::get_user_by_name_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& cb,
            const std::string& path_username)
            {
            try {
                /* -------- parameter extraction -------- */



                /* -------- delegate to service -------- */
            getUserByNameResponse respVariant;
                service->get_user_by_name(
            path_username
                respVariant);

                /* -------- serialize & return -------- */
                auto resp = org::openapitools::server::helpers::variantToHttp(respVariant);
                cb(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            cb(resp);
            }
            }
            /* ---------- loginUser ---------- */
            void UserApi::login_user_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& cb,
            const std::optional<std::string>& query_username,
            const std::optional<std::string>& query_password)
            {
            try {
                /* -------- parameter extraction -------- */

                        {
                        auto _q = req->getParameter("username");
                        std::optional<std::string> username;
                        if (!_q.empty()) {
                    std::string tmp;
                        if (fromStringValue(_q, tmp))
                    username = tmp;
                        }
                        }
                        {
                        auto _q = req->getParameter("password");
                        std::optional<std::string> password;
                        if (!_q.empty()) {
                    std::string tmp;
                        if (fromStringValue(_q, tmp))
                    password = tmp;
                        }
                        }


                /* -------- delegate to service -------- */
            loginUserResponse respVariant;
                service->login_user(
            query_username, query_password
                respVariant);

                /* -------- serialize & return -------- */
                auto resp = org::openapitools::server::helpers::variantToHttp(respVariant);
                cb(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            cb(resp);
            }
            }
            /* ---------- logoutUser ---------- */
            void UserApi::logout_user_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& cb)
            {
            try {
                /* -------- parameter extraction -------- */



                /* -------- delegate to service -------- */
            logoutUserResponse respVariant;
                service->logout_user(
            
                respVariant);

                /* -------- serialize & return -------- */
                auto resp = org::openapitools::server::helpers::variantToHttp(respVariant);
                cb(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            cb(resp);
            }
            }
            /* ---------- updateUser ---------- */
            void UserApi::update_user_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& cb,
            const std::string& path_username)
            {
            try {
                /* -------- parameter extraction -------- */
                        User user;
                            try {
                            Json::Value jsonBody;
                            Json::Reader reader;
                            if (!reader.parse(req->getBody(), jsonBody))
                            throw std::invalid_argument("Invalid JSON body");
                            from_json(jsonBody, user);
                        user.validate();
                            } catch (const std::exception& e) {
                            handleParsingException(e, std::move(cb));
                            return;
                            }



                /* -------- delegate to service -------- */
            updateUserResponse respVariant;
                service->update_user(
            path_username, user
                respVariant);

                /* -------- serialize & return -------- */
                auto resp = org::openapitools::server::helpers::variantToHttp(respVariant);
                cb(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            cb(resp);
            }
            }

        void UserApi::user_api_default_handler(
        const drogon::HttpRequestPtr& /*req*/,
        std::function<void (const drogon::HttpResponsePtr &)>&& cb)
        {
        auto resp = drogon::HttpResponse::newHttpResponse("The requested method does not exist");
        resp->setStatusCode(drogon::k404NotFound);
        cb(resp);
        }

        } // namespace org::openapitools::server::api

