/**
* OpenAPI Petstore
* This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
 * UserApiImpl.h  –  concrete implementation of UserApiInterface
 *
 * 
 */
#ifndef USER_API_IMPL_H_
#define USER_API_IMPL_H_

/* ----------------------------------------------------------------------
 *  Includes
 * -------------------------------------------------------------------- */

#include <drogon/HttpTypes.h>
#include <memory>
#include <optional>

#include "UserApiInterface.h"    /* generated abstract interface */

#include "User.h"
#include <string>
#include <vector>

namespace org::openapitools::server::api
{

using namespace org::openapitools::server::model;     /* DTO namespace (optional) */

/* ======================================================================
 *  Concrete service class
 * ==================================================================== */
class  UserApiImpl final : public UserApiInterface
{
public:
    UserApiImpl()  = default;
    ~UserApiImpl() override = default;

    /* ------------- createUser ------------- */
    void create_user(
        const User &user
        , 
        createUserResponse &response
    ) override;
    /* ------------- createUsersWithArrayInput ------------- */
    void create_users_with_array_input(
        const std::vector<org::openapitools::server::model::User> &user
        , 
        createUsersWithArrayInputResponse &response
    ) override;
    /* ------------- createUsersWithListInput ------------- */
    void create_users_with_list_input(
        const std::vector<org::openapitools::server::model::User> &user
        , 
        createUsersWithListInputResponse &response
    ) override;
    /* ------------- deleteUser ------------- */
    void delete_user(
        const std::string &path_username
        , 
        deleteUserResponse &response
    ) override;
    /* ------------- getUserByName ------------- */
    void get_user_by_name(
        const std::string &path_username
        , 
        getUserByNameResponse &response
    ) override;
    /* ------------- loginUser ------------- */
    void login_user(
        const std::optional<std::string> &query_username, 
                const std::optional<std::string> &query_password
        , 
        loginUserResponse &response
    ) override;
    /* ------------- logoutUser ------------- */
    void logout_user(

        logoutUserResponse &response
    ) override;
    /* ------------- updateUser ------------- */
    void update_user(
        const std::string &path_username, 
                const User &user
        , 
        updateUserResponse &response
    ) override;
};

} /* namespace org::openapitools::server::api */

#endif /* _IMPL_H_ */
