/**
* OpenAPI Petstore
* This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

    #include "UserApi.h"
    #include "Helpers.h"
    #include <json/json.h>

    namespace org::openapitools::server::api
    {

    using namespace org::openapitools::server::helpers;
        using namespace org::openapitools::server::model;

    const std::string UserApi::base = "/v2";

    void UserApi::handleParsingException(
    const std::exception& ex,
    std::function<void (const drogon::HttpResponsePtr &)>&& callback) const noexcept
        {
        auto [status, body] = handleParsingException(ex);
        auto resp          = drogon::HttpResponse::newHttpResponse(body);
        resp->setStatusCode(status);
        callback(resp);
        }

        std::pair<drogon::HttpStatusCode, std::string>
    UserApi::handleParsingException(const std::exception& ex) const noexcept
        {
        try { throw; }
        catch (Json::Exception&               e) { return {drogon::k400BadRequest, e.what()}; }
        catch (ValidationException&           e) { return {drogon::k400BadRequest, e.what()}; }
        catch (std::exception&                e) { return {drogon::k500InternalServerError, e.what()}; }
        }

        void UserApi::handleOperationException(
        const std::exception& ex,
        std::function<void (const drogon::HttpResponsePtr &)>&& callback) const noexcept
        {
        auto [status, body] = handleOperationException(ex);
        auto resp          = drogon::HttpResponse::newHttpResponse(body);
        resp->setStatusCode(status);
        callback(resp);
        }

        std::pair<drogon::HttpStatusCode, std::string>
    UserApi::handleOperationException(const std::exception& ex) const noexcept
        {
        return {drogon::k500InternalServerError, ex.what()};
        }

            /* ---------- createUser ---------- */
            void UserApi::create_user_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& callback)
            {
            try {
                /* --------‑‑‑ parameter extraction ‑‑‑--------- */

                    // Body parameter
                        User user;
                            try {
                            Json::Value jsonBody;
                            Json::Reader reader;
                            if (!reader.parse(req->getBody(), jsonBody))
                            throw std::invalid_argument("Invalid JSON body");
                            from_json(jsonBody, user);
                        user.validate();
                            } catch (const std::exception& e) {
                            handleParsingException(e, std::move(callback));
                            return;
                            }


                /* ---------- call service ---------- */
            createUserResponse response;
                service->create_user(
            user, response);

                /* ---------- serialize & return ---------- */
                // You can convert `response` (std::variant) to HttpResponse here.
                // For now just return 501.
                auto resp = drogon::HttpResponse::newHttpResponse("Not implemented");
                resp->setStatusCode(drogon::k501NotImplemented);
                callback(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            callback(resp);
            }
            }
            /* ---------- createUsersWithArrayInput ---------- */
            void UserApi::create_users_with_array_input_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& callback)
            {
            try {
                /* --------‑‑‑ parameter extraction ‑‑‑--------- */

                    // Body parameter
                        User user;
                            try {
                            Json::Value jsonBody;
                            Json::Reader reader;
                            if (!reader.parse(req->getBody(), jsonBody))
                            throw std::invalid_argument("Invalid JSON body");
                            from_json(jsonBody, user);
                        user.validate();
                            } catch (const std::exception& e) {
                            handleParsingException(e, std::move(callback));
                            return;
                            }


                /* ---------- call service ---------- */
            createUsersWithArrayInputResponse response;
                service->create_users_with_array_input(
            user, response);

                /* ---------- serialize & return ---------- */
                // You can convert `response` (std::variant) to HttpResponse here.
                // For now just return 501.
                auto resp = drogon::HttpResponse::newHttpResponse("Not implemented");
                resp->setStatusCode(drogon::k501NotImplemented);
                callback(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            callback(resp);
            }
            }
            /* ---------- createUsersWithListInput ---------- */
            void UserApi::create_users_with_list_input_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& callback)
            {
            try {
                /* --------‑‑‑ parameter extraction ‑‑‑--------- */

                    // Body parameter
                        User user;
                            try {
                            Json::Value jsonBody;
                            Json::Reader reader;
                            if (!reader.parse(req->getBody(), jsonBody))
                            throw std::invalid_argument("Invalid JSON body");
                            from_json(jsonBody, user);
                        user.validate();
                            } catch (const std::exception& e) {
                            handleParsingException(e, std::move(callback));
                            return;
                            }


                /* ---------- call service ---------- */
            createUsersWithListInputResponse response;
                service->create_users_with_list_input(
            user, response);

                /* ---------- serialize & return ---------- */
                // You can convert `response` (std::variant) to HttpResponse here.
                // For now just return 501.
                auto resp = drogon::HttpResponse::newHttpResponse("Not implemented");
                resp->setStatusCode(drogon::k501NotImplemented);
                callback(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            callback(resp);
            }
            }
            /* ---------- deleteUser ---------- */
            void UserApi::delete_user_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& callback,
            const std::string& path_username)
            {
            try {
                /* --------‑‑‑ parameter extraction ‑‑‑--------- */
                    // Path parameters
                        // auto username = /* extract from route */ ;



                /* ---------- call service ---------- */
            deleteUserResponse response;
                service->delete_user(
            path_username, response);

                /* ---------- serialize & return ---------- */
                // You can convert `response` (std::variant) to HttpResponse here.
                // For now just return 501.
                auto resp = drogon::HttpResponse::newHttpResponse("Not implemented");
                resp->setStatusCode(drogon::k501NotImplemented);
                callback(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            callback(resp);
            }
            }
            /* ---------- getUserByName ---------- */
            void UserApi::get_user_by_name_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& callback,
            const std::string& path_username)
            {
            try {
                /* --------‑‑‑ parameter extraction ‑‑‑--------- */
                    // Path parameters
                        // auto username = /* extract from route */ ;



                /* ---------- call service ---------- */
            getUserByNameResponse response;
                service->get_user_by_name(
            path_username, response);

                /* ---------- serialize & return ---------- */
                // You can convert `response` (std::variant) to HttpResponse here.
                // For now just return 501.
                auto resp = drogon::HttpResponse::newHttpResponse("Not implemented");
                resp->setStatusCode(drogon::k501NotImplemented);
                callback(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            callback(resp);
            }
            }
            /* ---------- loginUser ---------- */
            void UserApi::login_user_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& callback,
            const std::optional<std::string>& query_username,
            const std::optional<std::string>& query_password)
            {
            try {
                /* --------‑‑‑ parameter extraction ‑‑‑--------- */


                    // Query parameters
                        {   /* username */
                        auto _q = req->getParameter("username");
                        std::optional<std::string> username;
                        if (!_q.empty()) {
                    std::string tmp;
                        if (fromStringValue(_q, tmp))
                    username = tmp;
                        }
                        }
                        {   /* password */
                        auto _q = req->getParameter("password");
                        std::optional<std::string> password;
                        if (!_q.empty()) {
                    std::string tmp;
                        if (fromStringValue(_q, tmp))
                    password = tmp;
                        }
                        }

                /* ---------- call service ---------- */
            loginUserResponse response;
                service->login_user(
            query_username, query_password, response);

                /* ---------- serialize & return ---------- */
                // You can convert `response` (std::variant) to HttpResponse here.
                // For now just return 501.
                auto resp = drogon::HttpResponse::newHttpResponse("Not implemented");
                resp->setStatusCode(drogon::k501NotImplemented);
                callback(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            callback(resp);
            }
            }
            /* ---------- logoutUser ---------- */
            void UserApi::logout_user_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& callback)
            {
            try {
                /* --------‑‑‑ parameter extraction ‑‑‑--------- */



                /* ---------- call service ---------- */
            logoutUserResponse response;
                service->logout_user(
            response);

                /* ---------- serialize & return ---------- */
                // You can convert `response` (std::variant) to HttpResponse here.
                // For now just return 501.
                auto resp = drogon::HttpResponse::newHttpResponse("Not implemented");
                resp->setStatusCode(drogon::k501NotImplemented);
                callback(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            callback(resp);
            }
            }
            /* ---------- updateUser ---------- */
            void UserApi::update_user_handler(
            const drogon::HttpRequestPtr& req,
            std::function<void (const drogon::HttpResponsePtr &)>&& callback,
            const std::string& path_username)
            {
            try {
                /* --------‑‑‑ parameter extraction ‑‑‑--------- */
                    // Path parameters
                        // auto username = /* extract from route */ ;

                    // Body parameter
                        User user;
                            try {
                            Json::Value jsonBody;
                            Json::Reader reader;
                            if (!reader.parse(req->getBody(), jsonBody))
                            throw std::invalid_argument("Invalid JSON body");
                            from_json(jsonBody, user);
                        user.validate();
                            } catch (const std::exception& e) {
                            handleParsingException(e, std::move(callback));
                            return;
                            }


                /* ---------- call service ---------- */
            updateUserResponse response;
                service->update_user(
            path_username, user, response);

                /* ---------- serialize & return ---------- */
                // You can convert `response` (std::variant) to HttpResponse here.
                // For now just return 501.
                auto resp = drogon::HttpResponse::newHttpResponse("Not implemented");
                resp->setStatusCode(drogon::k501NotImplemented);
                callback(resp);


            } catch (const std::exception& e) {
            auto resp = drogon::HttpResponse::newHttpResponse(e.what());
            resp->setStatusCode(drogon::k500InternalServerError);
            callback(resp);
            }
            }

        void UserApi::user_api_default_handler(
        const drogon::HttpRequestPtr&               /*req*/,
        std::function<void (const drogon::HttpResponsePtr &)>&& callback)
        {
        auto resp = drogon::HttpResponse::newHttpResponse("The requested method does not exist");
        resp->setStatusCode(drogon::k404NotFound);
        callback(resp);
        }

        } // namespace org::openapitools::server::api

