/**
* OpenAPI Petstore
* This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * UserApiInterface.h
 *
 * 
 */
#ifndef USER_API_INTERFACE_H_
#define USER_API_INTERFACE_H_


#include <drogon/HttpTypes.h>
#include <optional>
#include <utility>
#include <variant>
#include <stdexcept>
#include "User.h"#include <string>#include <vector>

namespace org::openapitools::server::api {

class  UserApiInterface {
public:
    virtual ~UserApiInterface() = default;

/* ---------- response variants ---------- */
    using createUserResponse = std::variant<
            
        std::integral_constant<drogon::HttpStatusCode,drogon::kUnknown>
                
            
    >;
    using createUsersWithArrayInputResponse = std::variant<
            
        std::integral_constant<drogon::HttpStatusCode,drogon::kUnknown>
                
            
    >;
    using createUsersWithListInputResponse = std::variant<
            
        std::integral_constant<drogon::HttpStatusCode,drogon::kUnknown>
                
            
    >;
    using deleteUserResponse = std::variant<
            
        std::integral_constant<drogon::HttpStatusCode,drogon::k400BadRequest>
                
            
            
        std::integral_constant<drogon::HttpStatusCode,drogon::k404NotFound>
                
            
    >;
    using getUserByNameResponse = std::variant<
            
        std::pair<std::integral_constant<drogon::HttpStatusCode,drogon::k200OK>,org::openapitools::server::model::User}>
,
            
        std::pair<std::integral_constant<drogon::HttpStatusCode,drogon::k200OK>,org::openapitools::server::model::User}>

            
            
        std::integral_constant<drogon::HttpStatusCode,drogon::k400BadRequest>
                
            
            
        std::integral_constant<drogon::HttpStatusCode,drogon::k404NotFound>
                
            
    >;
    using loginUserResponse = std::variant<
            
        std::pair<std::integral_constant<drogon::HttpStatusCode,drogon::k200OK>,std::string}>
,
            
        std::pair<std::integral_constant<drogon::HttpStatusCode,drogon::k200OK>,std::string}>

            
            
        std::integral_constant<drogon::HttpStatusCode,drogon::k400BadRequest>
                
            
    >;
    using logoutUserResponse = std::variant<
            
        std::integral_constant<drogon::HttpStatusCode,drogon::kUnknown>
                
            
    >;
    using updateUserResponse = std::variant<
            
        std::integral_constant<drogon::HttpStatusCode,drogon::k400BadRequest>
                
            
            
        std::integral_constant<drogon::HttpStatusCode,drogon::k404NotFound>
                
            
    >;

/* ---------- abstract operations ---------- */
    /// <summary>Create user</summary>
    /// <remarks>This can only be done by the logged in user.</remarks>
    /// <param name="user">Created user object</param>
    virtual void create_user(
        const org::openapitools::server::model::User& user, 
        createUserResponse& response) = 0;


    /// <summary>Creates list of users with given input array</summary>
    /// <remarks></remarks>
    /// <param name="user">List of user object</param>
    virtual void create_users_with_array_input(
        const std::vector<org::openapitools::server::model::User>& user, 
        createUsersWithArrayInputResponse& response) = 0;


    /// <summary>Creates list of users with given input array</summary>
    /// <remarks></remarks>
    /// <param name="user">List of user object</param>
    virtual void create_users_with_list_input(
        const std::vector<org::openapitools::server::model::User>& user, 
        createUsersWithListInputResponse& response) = 0;


    /// <summary>Delete user</summary>
    /// <remarks>This can only be done by the logged in user.</remarks>
    /// <param name="path_username">The name that needs to be deleted</param>
    virtual void delete_user(
        const std::string& path_username, 
        deleteUserResponse& response) = 0;


    /// <summary>Get user by user name</summary>
    /// <remarks></remarks>
    /// <param name="path_username">The name that needs to be fetched. Use user1 for testing.</param>
    virtual void get_user_by_name(
        const std::string& path_username, 
        getUserByNameResponse& response) = 0;


    /// <summary>Logs user into the system</summary>
    /// <remarks></remarks>
    /// <param name="query_username">The user name for login</param>/// <param name="query_password">The password for login in clear text</param>
    virtual void login_user(
        const std::optional<std::string>& query_username,         const std::optional<std::string>& query_password, 
        loginUserResponse& response) = 0;


    /// <summary>Logs out current logged in user session</summary>
    /// <remarks></remarks>
    
    virtual void logout_user(

        logoutUserResponse& response) = 0;


    /// <summary>Updated user</summary>
    /// <remarks>This can only be done by the logged in user.</remarks>
    /// <param name="path_username">name that need to be deleted</param>/// <param name="user">Updated user object</param>
    virtual void update_user(
        const std::string& path_username,         const org::openapitools::server::model::User& user, 
        updateUserResponse& response) = 0;


};

} // namespace org::openapitools::server::api
#endif /* USER_API_INTERFACE_H_ */
