/**
* OpenAPI Petstore
* This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include <drogon/drogon.h>
#include <memory>
    #include <thread>

    
        #include "PetApi.h"          // Generated controller
    
        #include "StoreApi.h"          // Generated controller
    
        #include "UserApi.h"          // Generated controller
    

    using namespace org::openapitools::server::api;

    int
    main(int /*argc*/, char* /*argv*/[])
    {
    /* -----------------------------------------------------------------------
    * 1. Core server settings
    * -------------------------------------------------------------------- */
    const unsigned short port =
    static_cast<unsigned short>(8080);
    const unsigned int threads =
    std::max(1u, std::thread::hardware_concurrency());   // sensible default

    drogon::app()
    .setThreadNum(threads)               // worker‑threads
    .addListener("0.0.0.0", port)        // bind address / port
    /* .enableRunAsDaemon()              // ← uncomment if you need daemon mode   */
    /* .setSSLFiles("server.pem","key")  // ← TLS example                        */
    ;

    /* -----------------------------------------------------------------------
    * 2. Register controllers
    *    (second template parameter = false ⇒ manual registration required)
    * -------------------------------------------------------------------- */
    
        drogon::app().registerController(std::make_shared<PetApi>());
    
        drogon::app().registerController(std::make_shared<StoreApi>());
    
        drogon::app().registerController(std::make_shared<UserApi>());
    

    /* -----------------------------------------------------------------------
    * 3. Start event loop (blocking)
    * -------------------------------------------------------------------- */
    drogon::app().run();

    return 0;
    }